### ISSUE TITLE
Async event handling is broken on HTML5

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Coroutines#12]
https://github.com/JujuAdams/Coroutines/blob/4e9f4ae392725931682ed14c702edc6855cc595f/scripts/CoroutineEventHook/CoroutineEventHook.gml#L57-L63

Extracting the correct event name based on `event_type` and `event_number` doesn't work in HTML5 for reasons I haven't yet looked into.

**Comment by offalynne** [comment]
https://yal.cc/r/gml/?mode=2d&ver=GMS2&tabs_lz=NobwRAdghgtgpmAXGAEnANug9gQjAGjAGMsATBZAekoAIBeASgB0AnJiV9gFxaiLgAUcAG4B9IizhQucBgG5OEHn0EjRAZxkAHUQCM4AcwCWEeYuX8hYzXC1m2S3pbU2dcCKXvcnqsaV4A7l4cDtQ0ACKIiuY+VqJQ6gCeEESiAXC6ohBwXAFYLADWJgbBFr7xSSlpGaWxagnJqepYREZQ6LUqcQ1V6lDCcKLYUJ4KDmXdlamkbdglY95d9VPVmTawnc5iPU2JNjCiIu5c8mAAvgC6QA
